import json
import asyncio
import time
from typing import AsyncGenerator
from fastapi import APIRouter, HTTPException, Request, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage

from src import retriever
from src.retriever import graph
from src.react_agent.tools import retrieved_nodes_var
from src.retriever.schemas import GeneratedAnswer
from src.api.auth import verify_jwt

router = APIRouter()

# Load the indices on module import so they are ready
# (Safe to call multiple times as it checks if already loaded)
retriever.load("tree")

class ChatRequest(BaseModel):
    message: str

def parse_message_content(content) -> str:
    """Helper to cleanly flatten content strings or lists of dicts."""
    if isinstance(content, str):
        return content
    elif isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, str):
                parts.append(part)
            elif isinstance(part, dict) and "text" in part:
                parts.append(part["text"])
            elif hasattr(part, "text"):
                parts.append(part.text)
        return "".join(parts)
    return str(content)

async def run_agent_stream(agent, thread_id: str, query: str) -> AsyncGenerator[str, None]:
    """Runs the LangGraph agent and yields SSE events showing thoughts, tool calls, and final answer."""
    start_time = time.time()
    
    # 1. Set up connection config
    config = {
        "configurable": {"thread_id": thread_id},
        "recursion_limit": 10
    }
    
    # 2. Setup ContextVar to collect retrieved nodes during execution
    collected_nodes = []
    token = retrieved_nodes_var.set(collected_nodes)
    
    try:
        # Stream updates from the agent
        async for event in agent.astream(
            {"messages": [HumanMessage(content=query)]},
            config=config,
            stream_mode="updates"
        ):
            for node, update in event.items():
                if node == "agent":
                    msgs = update.get("messages", [])
                    if msgs:
                        msg = msgs[-1]
                        content = parse_message_content(msg.content)
                        if content:
                            yield f"data: {json.dumps({'type': 'thought', 'content': content.strip()})}\n\n"
                        
                        # Stream tool calls if any
                        if hasattr(msg, "tool_calls") and msg.tool_calls:
                            for tc in msg.tool_calls:
                                yield f"data: {json.dumps({'type': 'tool_call', 'name': tc['name'], 'args': tc['args']})}\n\n"
                                
                elif node == "tools":
                    msgs = update.get("messages", [])
                    if msgs:
                        msg = msgs[-1]
                        content = parse_message_content(msg.content)
                        # Yield truncated observation preview to keep SSE package light
                        preview = content[:300] + "..." if len(content) > 300 else content
                        yield f"data: {json.dumps({'type': 'observation', 'content': preview.strip()})}\n\n"

        # 3. Retrieve final state to extract the structured answer
        state = await agent.aget_state(config)
        generated: GeneratedAnswer = state.values.get("structured_response")
        
        if not generated:
            raise ValueError("No structured answer was generated by the agent.")
            
        latency = round((time.time() - start_time) * 1000)
        
        # 4. Resolve citations
        citations_list = []
        if generated.citations:
            for cid in generated.citations:
                node = graph._corpus_index.get_node(cid) if graph._corpus_index else None
                if node:
                    citations_list.append({
                        "node_id": cid,
                        "title": node.get("title", ""),
                        "page_range": node.get("metadata", {}).get("page_range", []),
                        "content": node.get("content", "")
                    })
                    
        # 5. Format key provisions
        key_provisions_formatted = []
        for kp in generated.key_provisions:
            kp_strip = kp.strip()
            if not kp_strip.startswith("-"):
                kp_strip = f"- {kp_strip}"
            key_provisions_formatted.append(kp_strip)

        # 6. Yield the final answer components
        payload = {
            "type": "final_answer",
            "answer_text": generated.answer_text,
            "key_provisions": key_provisions_formatted,
            "citations": citations_list,
            "is_insufficient_context": generated.is_insufficient_context,
            "confidence": 0.0 if generated.is_insufficient_context else 1.0,
            "latency_ms": latency
        }
        yield f"data: {json.dumps(payload)}\n\n"
        
    except Exception as e:
        yield f"data: {json.dumps({'type': 'error', 'content': f'API streaming error: {str(e)}'})}\n\n"
    finally:
        retrieved_nodes_var.reset(token)

@router.post("/chats/{thread_id}/message")
async def chat_message(
    thread_id: str,
    payload: ChatRequest,
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Streams the ReAct agent thought process and final response as Server-Sent Events (SSE)."""
    agent = request.app.state.agent
    # Scope thread_id by user_id to isolate histories between users securely
    scoped_thread_id = f"{user['sub']}:{thread_id}"
    return StreamingResponse(
        run_agent_stream(agent, scoped_thread_id, payload.message),
        media_type="text/event-stream"
    )

@router.get("/chats/{thread_id}/history")
async def get_chat_history(
    thread_id: str,
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Retrieves thread message history from SQLite checkpointer, populating reasoning steps, citations, and key provisions."""
    try:
        agent = request.app.state.agent
        scoped_thread_id = f"{user['sub']}:{thread_id}"
        config = {"configurable": {"thread_id": scoped_thread_id}}
        
        # 1. Fetch checkpoints history chronologically (oldest first)
        snapshots = []
        async for s in agent.aget_state_history(config):
            snapshots.append(s)
        snapshots.reverse()
        
        formatted_messages = []
        prev_msg_count = 0
        
        for snapshot in snapshots:
            # Checkpoints where 'next' is empty signify completed conversational turns
            if not snapshot.next:
                messages = snapshot.values.get("messages", [])
                turn_messages = messages[prev_msg_count:]
                prev_msg_count = len(messages)
                
                user_content = ""
                assistant_content = ""
                steps = []
                
                for m in turn_messages:
                    if isinstance(m, HumanMessage):
                        user_content = parse_message_content(m.content)
                    elif isinstance(m, AIMessage):
                        if m.tool_calls:
                            content = parse_message_content(m.content) or ""
                            if content.strip():
                                steps.append({"type": "thought", "content": content.strip()})
                            for tc in m.tool_calls:
                                steps.append({
                                    "type": "tool_call",
                                    "content": f"Calling tool: {tc['name']} with parameters: {tc['args']}"
                                })
                        else:
                            assistant_content = parse_message_content(m.content)
                    elif isinstance(m, ToolMessage):
                        content = parse_message_content(m.content)
                        preview = content[:300] + "..." if len(content) > 300 else content
                        steps.append({"type": "observation", "content": preview.strip()})
                
                # Fetch structured response (citations/key provisions) from the snapshot values
                structured = snapshot.values.get("structured_response")
                citations_list = []
                key_provisions_list = []
                
                if structured:
                    assistant_content = structured.answer_text
                    key_provisions_list = structured.key_provisions
                    
                    # Resolve citation titles and page ranges
                    if structured.citations:
                        for cid in structured.citations:
                            node = graph._corpus_index.get_node(cid) if graph._corpus_index else None
                            if node:
                                citations_list.append({
                                    "node_id": cid,
                                    "title": node.get("title", ""),
                                    "page_range": node.get("metadata", {}).get("page_range", []),
                                    "content": node.get("content", "")
                                })
                            else:
                                citations_list.append({
                                    "node_id": cid,
                                    "title": f"Citation: {cid.replace('_', ' ')}",
                                    "page_range": []
                                })
                
                if user_content:
                    formatted_messages.append({"role": "user", "content": user_content})
                if assistant_content or steps:
                    formatted_messages.append({
                        "role": "assistant",
                        "content": assistant_content,
                        "steps": steps,
                        "citations": citations_list,
                        "key_provisions": key_provisions_list
                    })
                    
        return {"thread_id": thread_id, "messages": formatted_messages}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load chat history: {str(e)}")

@router.delete("/chats/{thread_id}/history")
async def clear_chat_history(
    thread_id: str,
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Deletes all checkpoints and writes for a given thread_id from Supabase Postgres database."""
    try:
        scoped_thread_id = f"{user['sub']}:{thread_id}"
        pool = request.app.state.pool
        
        # Deleting all checkpoints, writes, and blobs for this user thread
        async with pool.connection() as conn:
            async with conn.cursor() as cur:
                await cur.execute("DELETE FROM checkpoints WHERE thread_id = %s", (scoped_thread_id,))
                await cur.execute("DELETE FROM checkpoint_blobs WHERE thread_id = %s", (scoped_thread_id,))
                await cur.execute("DELETE FROM checkpoint_writes WHERE thread_id = %s", (scoped_thread_id,))
                
        return {"status": "success", "message": f"Successfully cleared checkpoints for thread: {thread_id}"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to clear checkpointer database: {str(e)}")

