import json
import asyncio
import time
from typing import AsyncGenerator
from fastapi import APIRouter, HTTPException, Request, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage

from src import retriever
from src.retriever import client
from src.retriever import graph
from src.react_agent.tools import retrieved_nodes_var
from src.retriever.schemas import GeneratedAnswer
from src.api.auth import verify_jwt, get_supabase_project_id
from supabase import create_client, Client
import os
router = APIRouter()

# Initialize Supabase Admin Client
def get_supabase_admin() -> Client:
    supabase_url = os.getenv("SUPABASE_URL") or os.getenv("NEXT_PUBLIC_SUPABASE_URL")
    if not supabase_url:
        project_id = get_supabase_project_id()
        supabase_url = f"https://{project_id}.supabase.co"
    
    service_role_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    if not service_role_key:
        raise RuntimeError("SUPABASE_SERVICE_ROLE_KEY environment variable is not set. Required for Admin API operations.")
        
    return create_client(supabase_url, service_role_key)


# Load the indices on module import so they are ready
# (Safe to call multiple times as it checks if already loaded)
retriever.load("tree")

class ChatRequest(BaseModel):
    message: str = Field(..., max_length=5000)

def parse_message_content(content) -> str:
    """Helper to cleanly flatten content strings or lists of dicts."""
    if isinstance(content, str):
        return content
    elif isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, str):
                parts.append(part)
            elif isinstance(part, dict) and "text" in part:
                parts.append(part["text"])
            elif hasattr(part, "text"):
                parts.append(part.text)
        return "".join(parts)
    return str(content)

async def run_agent_stream(agent, thread_id: str, query: str, pool=None) -> AsyncGenerator[str, None]:
    """Runs the LangGraph agent and yields SSE events showing thoughts, tool calls, and final answer."""
    start_time = time.time()
    
    # 1. Set up connection config
    config = {
        "configurable": {"thread_id": thread_id},
        "recursion_limit": 10
    }
    
    # 2. Setup ContextVar to collect retrieved nodes during execution
    collected_nodes = []
    token = retrieved_nodes_var.set(collected_nodes)
    
    try:
        # Stream updates from the agent
        async for event in agent.astream(
            {"messages": [HumanMessage(content=query)]},
            config=config,
            stream_mode="updates"
        ):
            for node, update in event.items():
                if node == "agent":
                    msgs = update.get("messages", [])
                    if msgs:
                        msg = msgs[-1]
                        content = parse_message_content(msg.content)
                        if content:
                            yield f"data: {json.dumps({'type': 'thought', 'content': content.strip()})}\n\n"
                        
                        # Stream tool calls if any
                        if hasattr(msg, "tool_calls") and msg.tool_calls:
                            for tc in msg.tool_calls:
                                yield f"data: {json.dumps({'type': 'tool_call', 'name': tc['name'], 'args': tc['args']})}\n\n"
                                
                elif node == "tools":
                    msgs = update.get("messages", [])
                    if msgs:
                        msg = msgs[-1]
                        content = parse_message_content(msg.content)
                        # Yield truncated observation preview to keep SSE package light
                        preview = content[:300] + "..." if len(content) > 300 else content
                        yield f"data: {json.dumps({'type': 'observation', 'content': preview.strip()})}\n\n"

        # 3. Retrieve final state to extract the structured answer
        state = await agent.aget_state(config)
        generated: GeneratedAnswer = state.values.get("structured_response")
        
        if not generated:
            raise ValueError("No structured answer was generated by the agent.")
            
        latency = round((time.time() - start_time) * 1000)
        
        # Update session title if it is currently "New Legal Chat"
        if pool:
            try:
                async with pool.connection() as conn:
                    async with conn.cursor() as cur:
                        await cur.execute(
                            "SELECT title FROM chat_sessions WHERE thread_id = %s",
                            (thread_id,)
                        )
                        row = await cur.fetchone()
                        if row and row[0] == "New Legal Chat":
                            new_title = getattr(generated, "chat_title", None)
                            if not new_title or not new_title.strip():
                                new_title = query[:27] + "..." if len(query) > 30 else query
                            
                            new_title = new_title.strip().replace('"', '').replace("'", "")
                            if new_title.endswith('.'):
                                new_title = new_title[:-1]
                            if len(new_title) > 50:
                                new_title = new_title[:47] + "..."
                                
                            await cur.execute(
                                "UPDATE chat_sessions SET title = %s WHERE thread_id = %s",
                                (new_title, thread_id)
                            )
                            yield f"data: {json.dumps({'type': 'title_generated', 'title': new_title})}\n\n"
            except Exception as title_err:
                print(f"[Title Update Error]: {title_err}")
        
        # 4. Resolve citations
        citations_list = []
        if generated.citations:
            for cid in generated.citations:
                node = graph._corpus_index.get_node(cid) if graph._corpus_index else None
                if node:
                    citations_list.append({
                        "node_id": cid,
                        "title": node.get("title", ""),
                        "page_range": node.get("metadata", {}).get("page_range", []),
                        "content": node.get("content", "")
                    })
                    
        # 5. Format key provisions
        key_provisions_formatted = []
        for kp in generated.key_provisions:
            kp_strip = kp.strip()
            if not kp_strip.startswith("-"):
                kp_strip = f"- {kp_strip}"
            key_provisions_formatted.append(kp_strip)

        # 6. Yield the final answer components
        payload = {
            "type": "final_answer",
            "answer_text": generated.answer_text,
            "key_provisions": key_provisions_formatted,
            "citations": citations_list,
            "suggested_follow_up_questions": getattr(generated, "suggested_follow_up_questions", []),
            "action_items": getattr(generated, "action_items", []),
            "is_insufficient_context": generated.is_insufficient_context,
            "confidence": 0.0 if generated.is_insufficient_context else 1.0,
            "latency_ms": latency
        }
        yield f"data: {json.dumps(payload)}\n\n"
        
    except Exception as e:
        yield f"data: {json.dumps({'type': 'error', 'content': f'API streaming error: {str(e)}'})}\n\n"
    finally:
        retrieved_nodes_var.reset(token)

@router.post("/chats/{thread_id}/message")
async def chat_message(
    thread_id: str,
    payload: ChatRequest,
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Streams the ReAct agent thought process and final response as Server-Sent Events (SSE)."""
    agent = request.app.state.agent
    # Scope thread_id by user_id to isolate histories between users securely
    scoped_thread_id = f"{user['sub']}:{thread_id}"
    pool = request.app.state.pool

    # Handle session creation with an Atomic UPSERT to avoid race conditions
    try:
        async with pool.connection() as conn:
            async with conn.cursor() as cur:
                fallback_title = "New Legal Chat"
                await cur.execute(
                    """
                    INSERT INTO chat_sessions (thread_id, user_id, title, updated_at)
                    VALUES (%s, %s, %s, CURRENT_TIMESTAMP)
                    ON CONFLICT (thread_id) 
                    DO UPDATE SET updated_at = CURRENT_TIMESTAMP
                    """,
                    (scoped_thread_id, user['sub'], fallback_title)
                )
    except Exception as db_err:
        print(f"[chat_message] DB tracking error: {db_err}")

    return StreamingResponse(
        run_agent_stream(agent, scoped_thread_id, payload.message, pool),
        media_type="text/event-stream"
    )

@router.get("/chats/{thread_id}/history")
async def get_chat_history(
    thread_id: str,
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Retrieves thread message history from SQLite checkpointer, populating reasoning steps, citations, and key provisions."""
    try:
        agent = request.app.state.agent
        scoped_thread_id = f"{user['sub']}:{thread_id}"
        config = {"configurable": {"thread_id": scoped_thread_id}}
        
        # 1. Fetch checkpoints history chronologically (oldest first)
        snapshots = []
        async for s in agent.aget_state_history(config):
            snapshots.append(s)
        snapshots.reverse()
        
        formatted_messages = []
        prev_msg_count = 0
        
        for snapshot in snapshots:
            # Checkpoints where 'next' is empty signify completed conversational turns
            if not snapshot.next:
                messages = snapshot.values.get("messages", [])
                turn_messages = messages[prev_msg_count:]
                prev_msg_count = len(messages)
                
                user_content = ""
                assistant_content = ""
                steps = []
                
                for m in turn_messages:
                    if isinstance(m, HumanMessage):
                        user_content = parse_message_content(m.content)
                    elif isinstance(m, AIMessage):
                        if m.tool_calls:
                            content = parse_message_content(m.content) or ""
                            if content.strip():
                                steps.append({"type": "thought", "content": content.strip()})
                            for tc in m.tool_calls:
                                steps.append({
                                    "type": "tool_call",
                                    "content": f"Calling tool: {tc['name']} with parameters: {tc['args']}"
                                })
                        else:
                            assistant_content = parse_message_content(m.content)
                    elif isinstance(m, ToolMessage):
                        content = parse_message_content(m.content)
                        preview = content[:300] + "..." if len(content) > 300 else content
                        steps.append({"type": "observation", "content": preview.strip()})
                
                # Fetch structured response (citations/key provisions) from the snapshot values
                structured = snapshot.values.get("structured_response")
                citations_list = []
                key_provisions_list = []
                
                if structured:
                    assistant_content = structured.answer_text
                    
                    key_provisions_formatted = []
                    if structured.key_provisions:
                        for kp in structured.key_provisions:
                            kp_strip = kp.strip()
                            if not kp_strip.startswith("-"):
                                kp_strip = f"- {kp_strip}"
                            key_provisions_formatted.append(kp_strip)
                    key_provisions_list = key_provisions_formatted
                    
                    # Resolve citation titles and page ranges
                    if structured.citations:
                        for cid in structured.citations:
                            node = graph._corpus_index.get_node(cid) if graph._corpus_index else None
                            if node:
                                citations_list.append({
                                    "node_id": cid,
                                    "title": node.get("title", ""),
                                    "page_range": node.get("metadata", {}).get("page_range", []),
                                    "content": node.get("content", "")
                                })
                            else:
                                citations_list.append({
                                    "node_id": cid,
                                    "title": f"Citation: {cid.replace('_', ' ')}",
                                    "page_range": []
                                })
                if user_content:
                    formatted_messages.append({"role": "user", "content": user_content})
                if assistant_content or steps:
                    formatted_messages.append({
                        "role": "assistant",
                        "content": assistant_content,
                        "steps": steps,
                        "citations": citations_list,
                        "key_provisions": key_provisions_list,
                        "suggested_follow_up_questions": getattr(structured, "suggested_follow_up_questions", []) if structured else [],
                        "action_items": getattr(structured, "action_items", []) if structured else []
                    })
                    
        return {"thread_id": thread_id, "messages": formatted_messages}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load chat history: {str(e)}")

@router.get("/chats/sessions")
async def get_chat_sessions(
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Retrieves all active chat sessions for the authenticated user, ordered by most recent."""
    try:
        pool = request.app.state.pool
        prefix = f"{user['sub']}:"
        
        async with pool.connection() as conn:
            async with conn.cursor() as cur:
                await cur.execute(
                    """
                    SELECT thread_id, title
                    FROM chat_sessions 
                    WHERE user_id = %s
                    ORDER BY updated_at DESC
                    """, 
                    (user['sub'],)
                )
                rows = await cur.fetchall()
                
        # thread_id format is "sub:real_thread_id"
        sessions = [{"id": row[0].replace(prefix, ""), "title": row[1]} for row in rows]
        return {"sessions": sessions}
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Failed to fetch sessions: {str(e)} - {traceback.format_exc()}")

@router.delete("/chats/{thread_id}/history")
async def clear_chat_history(
    thread_id: str,
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Deletes all checkpoints, writes, blobs, and the session mapping itself for a given thread_id."""
    try:
        scoped_thread_id = f"{user['sub']}:{thread_id}"
        pool = request.app.state.pool
        
        async with pool.connection() as conn:
            async with conn.transaction():
                async with conn.cursor() as cur:
                    await cur.execute("DELETE FROM checkpoints WHERE thread_id = %s", (scoped_thread_id,))
                    await cur.execute("DELETE FROM checkpoint_blobs WHERE thread_id = %s", (scoped_thread_id,))
                    await cur.execute("DELETE FROM checkpoint_writes WHERE thread_id = %s", (scoped_thread_id,))
                    await cur.execute("DELETE FROM chat_sessions WHERE thread_id = %s", (scoped_thread_id,))
                
        return {"status": "success", "message": f"Successfully deleted session and checkpoints for thread: {thread_id}"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete session: {str(e)}")

@router.delete("/users/me")
async def delete_user(
    request: Request,
    user: dict = Depends(verify_jwt)
):
    """Deletes the user's account and all associated chat sessions and history."""
    try:
        user_id = user.get("sub")
        if not user_id or user_id == "guest":
            raise HTTPException(status_code=400, detail="Guest users cannot delete accounts")
            
        pool = request.app.state.pool
        
        async with pool.connection() as conn:
            async with conn.transaction():
                async with conn.cursor() as cur:
                    # 1. Fetch all thread IDs for this user first
                    await cur.execute(
                        "SELECT thread_id FROM chat_sessions WHERE user_id = %s",
                        (user_id,)
                    )
                    rows = await cur.fetchall()
                    thread_ids = [row[0] for row in rows]
                    
                    # 2. Delete checkpoints, writes, and blobs using ANY(%s)
                    if thread_ids:
                        await cur.execute("DELETE FROM checkpoints WHERE thread_id = ANY(%s)", (thread_ids,))
                        await cur.execute("DELETE FROM checkpoint_blobs WHERE thread_id = ANY(%s)", (thread_ids,))
                        await cur.execute("DELETE FROM checkpoint_writes WHERE thread_id = ANY(%s)", (thread_ids,))
                    
                    # 3. Delete chat sessions mapping
                    await cur.execute("DELETE FROM chat_sessions WHERE user_id = %s", (user_id,))
        
        # 4. Delete user using the official Supabase Admin API
        supabase_admin = get_supabase_admin()
        
        # Run the synchronous Supabase client call in a separate thread to prevent 
        # blocking the FastAPI asyncio event loop, which can cause deadlocks on Windows.
        await asyncio.to_thread(supabase_admin.auth.admin.delete_user, user_id)
                
        return {"status": "success", "message": "Account and all history deleted successfully"}
    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete account: {str(e)}")

